# Generated by Django 5.1.2 on 2024-10-12 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('kilometraje', models.PositiveIntegerField()),
                ('numero_chasis', models.CharField(max_length=30, unique=True)),
                ('numero_motor', models.CharField(max_length=30, unique=True)),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.patente')),
            ],
        ),
    ]
