# Generated by Django 5.1.2 on 2024-10-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='patente',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Patente',
        ),
    ]
