# Generated by Django 5.1.2 on 2024-10-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_alter_automovil_patente_delete_patente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='automovil',
            options={'verbose_name_plural': 'Automóviles'},
        ),
    ]
