# Generated by Django 5.1.2 on 2024-10-13 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0006_vtv_automovil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coberturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('monto', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('franquicia', models.PositiveIntegerField()),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operacion.coberturas')),
            ],
        ),
    ]
