# Generated by Django 5.1.2 on 2024-10-13 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0007_coberturas_poliza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coberturas',
            name='monto',
        ),
    ]
