# Generated by Django 5.1.2 on 2024-10-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0010_alter_poliza_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vtv',
            options={'verbose_name_plural': 'VTV'},
        ),
    ]
