# Generated by Django 5.1.2 on 2024-10-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0011_alter_vtv_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtvEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
