# Generated by Django 5.1.2 on 2024-10-13 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0012_vtvestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtv',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operacion.vtvestado'),
        ),
    ]
