# Generated by Django 5.1.2 on 2024-10-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0013_alter_vtv_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteparticular',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='clienteparticular',
            name='telefono',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
