# Generated by Django 5.1.2 on 2024-10-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0014_alter_clienteparticular_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteparticular',
            name='telefono',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
