# Generated by Django 5.1.2 on 2024-10-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0015_alter_clienteparticular_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteparticular',
            name='telefono',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
