# Generated by Django 5.1.2 on 2024-10-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0018_alter_clienteparticular_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteempresa',
            name='telefono',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
