# Generated by Django 5.1.2 on 2024-10-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0019_alter_clienteempresa_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coberturas',
            options={'verbose_name_plural': 'Coberturas'},
        ),
    ]
