# Generated by Django 5.1.2 on 2024-10-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0020_alter_coberturas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteempresa',
            options={'verbose_name_plural': 'Cliente empresa'},
        ),
        migrations.AlterModelOptions(
            name='clienteparticular',
            options={'verbose_name_plural': 'Cliente particular'},
        ),
        migrations.AlterModelOptions(
            name='vtvestado',
            options={'verbose_name_plural': 'VTV estado'},
        ),
    ]
