# Generated by Django 5.1.2 on 2024-10-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0021_alter_clienteempresa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomovilEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('kilometraje', models.PositiveIntegerField()),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operacion.poliza')),
                ('vtv', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operacion.vtvestado')),
            ],
            options={
                'verbose_name_plural': 'Automóvil Estado',
            },
        ),
    ]
