# Generated by Django 5.1.2 on 2024-10-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0022_automovilestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automovilestado',
            old_name='poliza',
            new_name='poliza_estado',
        ),
        migrations.RenameField(
            model_name='automovilestado',
            old_name='vtv',
            new_name='vtv_estado',
        ),
    ]
