# Generated by Django 5.1.2 on 2024-10-13 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0024_remove_automovilestado_poliza_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovilestado',
            name='poliza_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='operacion.poliza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automovilestado',
            name='vtv_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='operacion.vtvestado'),
            preserve_default=False,
        ),
    ]
