# Generated by Django 5.1.2 on 2024-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0025_automovilestado_poliza_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteparticular',
            name='telefono',
            field=models.CharField(default='', max_length=50),
        ),
    ]
