# Generated by Django 5.1.2 on 2024-10-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0026_alter_clienteparticular_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovilestado',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='automovilestado',
            name='kilometraje',
        ),
        migrations.RemoveField(
            model_name='automovilestado',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='automovilestado',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='automovilestado',
            name='patente',
        ),
    ]
