# Generated by Django 5.1.2 on 2024-10-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0027_remove_automovilestado_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovilestado',
            name='patente_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='operacion.automovil'),
            preserve_default=False,
        ),
    ]
