# Generated by Django 5.1.2 on 2024-10-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0028_automovilestado_patente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovilestado',
            name='patente_estado',
        ),
    ]
