# Generated by Django 5.1.2 on 2024-10-13 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0029_remove_automovilestado_patente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtv',
            name='automovil',
        ),
        migrations.AddField(
            model_name='automovil',
            name='vtv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='operacion.vtv'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AutomovilEstado',
        ),
    ]
