# Generated by Django 4.2.17 on 2024-12-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0030_remove_vtv_automovil_automovil_vtv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='visibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
