# Generated by Django 5.1.3 on 2024-12-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0032_clienteparticular_visible_alter_automovil_vtv'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteempresa',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
