# Generated by Django 5.1.4 on 2025-01-03 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0033_clienteempresa_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='vtv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operacion.vtv'),
        ),
    ]
