# Generated by Django 5.1.4 on 2025-01-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0034_alter_automovil_vtv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno_VTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateTimeField()),
                ('lugar_verificacion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='operacion.automovil')),
            ],
        ),
    ]
