# Generated by Django 5.1.4 on 2025-01-14 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0035_turno_vtv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50)),
                ('dni', models.PositiveBigIntegerField(unique=True)),
                ('cuil', models.PositiveBigIntegerField(unique=True)),
                ('cuit', models.PositiveBigIntegerField(unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cliente empresa',
            },
        ),
        migrations.CreateModel(
            name='Flota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operacion.cliente')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operacion.seguro')),
            ],
            options={
                'verbose_name_plural': 'Flotas',
            },
        ),
    ]
