# Generated by Django 5.1.4 on 2025-01-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0036_cliente_flota'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='flota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='operacion.flota'),
        ),
    ]
