# Generated by Django 5.1.4 on 2025-01-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0037_automovil_flota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flota',
            name='nombre',
        ),
        migrations.AddField(
            model_name='flota',
            name='descripcion',
            field=models.CharField(default='AUTOCAR', max_length=50),
            preserve_default=False,
        ),
    ]
