# Generated by Django 5.1.4 on 2025-01-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0038_remove_flota_nombre_flota_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteEmpresa',
        ),
        migrations.DeleteModel(
            name='ClienteParticular',
        ),
        migrations.AddField(
            model_name='flota',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
