# Generated by Django 5.1.4 on 2025-01-19 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0039_delete_clienteempresa_delete_clienteparticular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_inicio_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_fin_mantenimiento', models.DateField(blank=True, null=True)),
                ('kilometraje', models.IntegerField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=50)),
                ('automovil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='operacion.automovil')),
            ],
            options={
                'ordering': ['fecha_inicio_mantenimiento'],
            },
        ),
        migrations.AddField(
            model_name='automovil',
            name='titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titular', to='operacion.titular'),
        ),
    ]
