# Generated by Django 5.1.3 on 2025-01-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0040_titular_mantenimiento_automovil_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno_vtv',
            name='vencimiento',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
