# Generated by Django 5.1.3 on 2025-01-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0041_turno_vtv_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno_vtv',
            name='vencimiento',
        ),
    ]
