# Generated by Django 5.1.4 on 2025-01-30 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0042_remove_turno_vtv_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la aseguradora')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
            },
        ),
        migrations.CreateModel(
            name='PolizaSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=50, verbose_name='Número de póliza')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de la póliza')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de vencimiento de la póliza')),
                ('cobertura', models.TextField(blank=True, null=True, verbose_name='Cobertura de la póliza')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Póliza activa?')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='operacion.aseguradora', verbose_name='Aseguradora')),
            ],
            options={
                'verbose_name': 'Póliza de seguro',
                'verbose_name_plural': 'Pólizas de seguro',
            },
        ),
    ]
