# Generated by Django 5.1.4 on 2025-01-31 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0043_aseguradora_polizaseguro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polizaseguro',
            name='cobertura',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='operacion.coberturas', verbose_name='Cobertura de la póliza'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Poliza',
        ),
    ]
