# Generated by Django 5.1.4 on 2025-01-31 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0044_alter_polizaseguro_cobertura_delete_poliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='operacion.polizaseguro'),
        ),
    ]
