# Generated by Django 5.1.4 on 2025-02-01 20:08

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0046_servicio_historialmantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='fecha_ultimo_servicio',
        ),
        migrations.RemoveField(
            model_name='historialmantenimiento',
            name='km_ultimo_servicio',
        ),
        migrations.AddField(
            model_name='automovil',
            name='fecha_ultimo_servicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automovil',
            name='km_ultimo_servicio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='costo_servicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='fecha_servicio_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='fecha_servicio_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmantenimiento',
            name='km_servicio',
            field=models.PositiveIntegerField(default=0)
            )
        ,
    
        migrations.AddField(
            model_name='historialmantenimiento',
            name='servicio_realizado',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.RESTRICT, to='operacion.servicio'),
            preserve_default=False,
        ),
    ]
