# Generated by Django 5.1.4 on 2025-02-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0049_marca_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
