# Generated by Django 5.1.4 on 2025-02-02 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0050_tiposiniestro'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='fecha_ultimo_siniestro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('severidad_daños', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('severo', 'Severo')], max_length=10)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cobertura_seguro', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='operacion.tiposiniestro')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='operacion.automovil')),
            ],
        ),
    ]
