# Generated by Django 5.1.3 on 2025-02-09 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0051_automovil_fecha_ultimo_siniestro_siniestro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovil',
            name='modelo',
        ),
        migrations.AlterField(
            model_name='automovil',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operacion.marca'),
        ),
    ]
