# Generated by Django 5.1.4 on 2025-02-12 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0052_remove_automovil_modelo_alter_automovil_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infracciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de acta')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora del acta')),
                ('infraccion', models.TextField(verbose_name='Descripción de la infracción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la multa')),
                ('puntos_descontar', models.IntegerField(default=0, verbose_name='Puntos a descontar')),
                ('puntos_reasignar', models.IntegerField(default=0, verbose_name='Puntos a reasignar')),
                ('lugar', models.CharField(max_length=255, verbose_name='Lugar de la infracción')),
                ('estado', models.TextField(verbose_name='Estado del acta')),
                ('legajo', models.CharField(max_length=20, verbose_name='Número de legajo')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='operacion.automovil', verbose_name='Auto asociado')),
            ],
        ),
    ]
