# Generated by Django 5.1.4 on 2025-02-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0053_infracciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAutomovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
