# Generated by Django 5.1.4 on 2025-02-12 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0054_estadoautomovil'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='Estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='operacion.estadoautomovil'),
        ),
    ]
