# Generated by Django 5.1.4 on 2025-02-12 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0055_automovil_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operacion.modelo'),
        ),
    ]
