# Generated by Django 5.1.3 on 2025-02-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0056_alter_automovil_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aseguradora',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección de la aseguradora'),
        ),
    ]
