# Generated by Django 5.1.3 on 2025-02-12 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0057_alter_aseguradora_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovil',
            name='numero_chasis',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nº de Chasis'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='numero_motor',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nº de Motor'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='operacion.polizaseguro', verbose_name='Póliza'),
        ),
    ]
