# Generated by Django 5.1.3 on 2025-02-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0059_alter_cliente_direccion_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flota',
            name='descripcion',
            field=models.CharField(max_length=1500, verbose_name='Descripción'),
        ),
    ]
