# Generated by Django 5.1.4 on 2025-02-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0060_alter_flota_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_firmado', models.BooleanField(default=False)),
                ('fecha_contrato_firmado', models.DateField(blank=True, null=True)),
                ('facturacion', models.BooleanField(default=False)),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.automovil')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacion.cliente')),
                ('flota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacion.flota')),
            ],
        ),
    ]
