# Generated by Django 5.1.4 on 2025-02-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0061_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='automovil',
            name='cantidad_de_sinistros',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
