# Generated by Django 5.1.4 on 2025-02-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0062_automovil_cantidad_de_sinistros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestro',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha del siniestro'),
        ),
    ]
