# Generated by Django 5.1.4 on 2025-02-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0063_alter_siniestro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestro',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del siniestro'),
        ),
    ]
