# Generated by Django 5.1.3 on 2025-02-24 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0064_alter_siniestro_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuil',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='C.U.I.L.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='C.U.I.T.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='D.N.I.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del siniestro'),
            preserve_default=False,
        ),
    ]
