# Generated by Django 5.1.3 on 2025-02-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0065_alter_cliente_cuil_alter_cliente_cuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='facturacion',
            field=models.BooleanField(default=False, verbose_name='Facturación'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='proximo_mantenimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='telefono',
            field=models.PositiveIntegerField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='titular',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
