# Generated by Django 5.1.4 on 2025-02-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0066_alter_contrato_facturacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguro',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
