# Generated by Django 5.1.4 on 2025-02-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0067_alter_seguro_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora de la nota')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=50)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la nota')),
            ],
        ),
    ]
