# Generated by Django 5.2.4 on 2025-07-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0069_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='monto_inicial',
            field=models.FloatField(default=76782),
            preserve_default=False,
        ),
    ]
