# Generated by Django 5.2.4 on 2025-07-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0070_contrato_monto_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_contrato_firmado',
            field=models.DateField(),
        ),
    ]
