# Generated by Django 5.2.4 on 2025-07-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0071_alter_contrato_fecha_contrato_firmado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={'ordering': ['prioridad', '-fecha']},
        ),
        migrations.AlterField(
            model_name='notas',
            name='prioridad',
            field=models.IntegerField(choices=[(3, 'Baja'), (2, 'Media'), (1, 'Alta')], default=2),
        ),
    ]
