# Generated by Django 5.2.4 on 2025-07-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0072_alter_notas_options_alter_notas_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notas',
            options={'ordering': ['prioridad', 'fecha']},
        ),
    ]
